### ISSUE TITLE
In vivo statistical maps with incorrect headers/affines

### ISSUE THREAD

**Issue by sitek** [sitek/subcortical-auditory-atlas#3]
sub-invivo_thresholded* and sub-invivo_exp1_unthresholded* , in the OSF data/space-mni directory
![image](https://user-images.githubusercontent.com/2488038/116482528-55ca3800-a853-11eb-9533-4452d2f09121.png)

@ofgulban

**Comment by ofgulban** [comment]
Sorry for late reply. I am looking into this.

**Comment by ofgulban** [comment]
Ok, finally a couple of update on this issue:

# Steps
1. It seems that we did not recognize this before as `sub-invivo_exp1_unthresholded*` and `sub-invivo_thresholded*` maps play well with `sub-bigbrain_MNI_conjunction_rois.nii.gz` when it was loaded as a `segmentation image` in ITKSNAP (See screenshot below).
![Screenshot_2021-08-06_17-49-27](https://user-images.githubusercontent.com/4668327/128537663-4a62f11c-8a79-4b3a-b555-406dcecfee09.png)

2. `sub-bigbrain_MNI_500um*` and `sub-bigbrain_MNI_100um*` images play well with each other when loaded into ITKSNAP in any order.

3. Therefore a quick fix can be done by updating the `affine` matrix in the nifti header of `sub-invivo*` maps. I have written a simple python script to do this:
```
import os
import nibabel as nb
import numpy as np

# File that needs to be fixed
NII1 = "/home/faruk/Documents/temp_aud_bstem_issue/sub-invivo_thresholded_activation_overlap_across_subjects_MNI_100um_bstem.nii.gz"
# Target
NII2 = "/home/faruk/Documents/temp_aud_bstem_issue/sub-bigbrain_MNI_100um_bstem_corrected.nii.gz"

# -----------------------------------------------------------------------------
nii1 = nb.load(NII1)
nii2 = nb.load(NII2)

# New nifti
img = nb.Nifti1Image(nii1.dataobj, affine=nii2.affine, header=nii1.header)
basename, ext = nii1.get_filename().split(os.extsep, 1)
out_name = '{}_{}.{}'.format(basename, "header_fixed", ext)
nb.save(img, out_name)

print("Finished.")
```

# Results
It seems that now the invivo statistical maps overlay correctly with whole brain MNI images:
![Screenshot_2021-08-06_18-04-33](https://user-images.githubusercontent.com/4668327/128539527-772803ed-c5a8-4818-8053-ead0333ab6be.png)

I have updated the following file in our OSF repository:
- `sub-invivo_thresholded_activation_overlap_across_subjects_MNI_100um_bstem.nii.gz` at <https://osf.io/yt5b4/>
- `sub-invivo_exp1_unthresholded_tvalues_group_average_MNI_100um_bstem.nii.gz` at <https://osf.io/rvxap/>

**Comment by ofgulban** [comment]
@sitek can you have a look at these updated files an confirm that the issue is resolved? Also, let me know if you encounter other files that needs this fix.

**Comment by sitek** [comment]
Awesome, thanks @ofgulban ! I'll take a look by next week just to confirm.

**Comment by sitek** [comment]
Got delayed, but looks great! Thanks Faruk.
